server:
  port: 8084
  servlet:
    context-path: /duke-order

spring:
  application:
    name: duke-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        file-extension: yml
  config:
    import:
      - nacos:duke-common.yml?refreshEnabled=true
      - nacos:duke-order.yml?refreshEnabled=true

swagger:
  title: 订单服务 API
  description: 订单服务鎺ュ彛鏂囨。
  version: 1.0.0
  enable-security: true


