server:
  port: 8083
  servlet:
    context-path: /demo

spring:
  application:
    name: duke-demo
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        file-extension: yml

  config:
    import:
      - nacos:duke-common.yml?refreshEnabled=true
      - nacos:duke-demo.yml?refreshEnabled=true

document:
  pipeline:
    chunk-size: 500
    overlap: 50
    batch-size: 5
    default-collection: documents

swagger:
  title: demo API
  description: demo接口文档
  version: 1.0.0
  enable-security: true
  server-url: http://localhost:8080/api/demo

