server:
  port: 8085
  servlet:
    context-path: /duke-notification

spring:
  application:
    name: duke-notification
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        file-extension: yml
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
  config:
    import:
      - nacos:duke-common.yml?refreshEnabled=true
      - nacos:duke-notification.yml?refreshEnabled=true

swagger:
  title: 通知服务 API
  description: 通知服务鎺ュ彛鏂囨。
  version: 1.0.0
  enable-security: false


